### ISSUE TITLE
Video has not been completely processed

### ISSUE THREAD

**Issue by iovart** [kijai/ComfyUI-LivePortraitKJ#28]
Just a few frames are being processed

https://github.com/kijai/ComfyUI-LivePortraitKJ/assets/157212332/61a911b0-d604-4ea4-afc5-bae48d7e367d

**Comment by kijai** [comment]
That's because the video loader node is set to load only 32 frames, and that example vid seems to have really high frame rate. So either increase the "select_every_nth" to skip frames, or increase the load cap:

![image](https://github.com/kijai/ComfyUI-LivePortraitKJ/assets/40791699/0cc16e5e-6578-46f1-8920-b87f0b3e3797)

**Comment by iovart** [comment]
Thanks!
